server:
  port: 8087
  servlet:
    context-path: /quet

spring:
  datasource:
    # Cập nhật URL cho phù hợp với MySQL của bạn, ví dụ:
    url: jdbc:mysql://localhost:3309/datastore
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "hRsmdMylV8s4YjNAM9Y9GYuUTjwmb++Jgg4wZ7SqjIqdnPE1grPXjEqNXgjrEd/5"
  valid-duration: 3600  # thời gian hợp lệ của token tính bằng giây
