server:
  port: 8087
  servlet:
    context-path: /quet
spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/test_android_system
    # url: jdbc:mysql://localhost:3306/traffic_management_system_new
    url: jdbc:mysql://localhost:3306/traffic_management_system_new_new

    username: root
    password: Tuankhang412
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "JxPPEpsMOmZsehp90kBaENU4t/MWgOP5m3G641l+Gx3dbh5sawYy6iKhsJLh3iJvGTiJhwoOU/MDhopdEllQDvSlatdIYMs4RJq9k1A9g2w="
  valid-duration: 3600  # thời gian hợp lệ của token tính bằng giây
python:
  service:
    url: http://127.0.0.1:8000/
app:
  image:
    directory: "D:/Programming_Language/Python/LearingFastAPI/imgmatch_api/Data/"
    accident: "D:/Programming_Language/BackEnd/Java/ITS_Minh/FIX_CODE_Dang_Lam/BE_UngDungQuetBienSoXe/src/main/java/com/example/licenseplate/image/"


goong:
  map:
    api:
      key: "Qlw9eguFkCeKQtRGdej4ABttAenBHvNRO7I46PKO"